### ISSUE TITLE
User changes email when subscribed to appointment notification topics

### ISSUE THREAD

**Issue by jhorne98** [YCPRadioTelescope/RT-Contracts#7]
Subscribing to an appointment notification topic requires an email and confirming the subscription through a confirmation email. A problem with this is when the user changes their email while currently subscribed to existing topics. Updating the existing subscriptions to the new email would require deleting all of the old subscriptions (which would probably require storing the appointments the user is subscribed to) and reconfirming all of the confirmation emails (which would be annoying for the user).

Handling it this way is possible with a small change to the user entity or the user can be warned that all previous notifications will not be updated.

**Comment by lgartrell** [comment]
**I'm a bit confused by this one,** not sure why we can send out updates to each of the user's appointments at time of email change. I think this would require writing a little SQL, but should have less of an impact than adding more things to the database.

Definitely do **not** want to bombard the user with reconfirmation emails for any appointment they may have had.

## Possible Plan
1. Investigate relationship between user & appointment notifications. Determine if my suggested change above is good, or if what Joel suggested with the additional column is what is needed. 
2. Write SQL Query, or add column to User
3. Test changes

## Teams Impacted
backend

**Comment by TUllery** [comment]
The actual error in our design is the assumption we would not change  the email. I believe this was a choice made at the beginning. A new email would be a new account, not a change in the attributes of the user - in other words, the email is the only identifier of the account. I think the mistake in the design is using user data as the primary key/identifier for the user. If we are going to allow users to change their email, I want to do it the right way. I want an estimate before approval to do this. When we add a new account/user, assign a primary key as an internal identity column in the database. Any lookup of the user at login would use the email as before, however, it will be easier to link notifications to the primary key than to an email value. Since a users primary key will never change, they have no access to it, then emails can be updated as easily as other attributes, just need the new email to be confirmed.

**Comment by lgartrell** [comment]
@TUllery Okay, that makes sense to me as well. This would involve changing the User schema. In addition to this change, with the expected notification to the admin app this involves the mobile team as well.

## Updated Plan
Backend | Mobile App
------------ | ----------------
Make changes to User schema as said by Todd | Investigate how to display notification received from backend
Support mobile team by sending a notification to the admin app on user signup | Create form for admin to either accept or deny a user
Test changes using existing testing / new testing | Test changes 

## Happy path (**This must work for this issue to be closed**)
1. new user signs up through website
2. backend processes new user, sends notification to admin app
3. private admin app receives notification, displays pop up to admin
4. Admin clicks pop up (or a sitting notification in the app itself)
5. Admin is delivered a form to accept or deny user
6. Based on admin choice, User is either deleted or approved (new flag in database for pending users)

**Comment by lgartrell** [comment]
@TUllery I see what you're saying, I think this work can be completed by the work on Issue #15, since they both relate to changes to the User Schema.

**Comment by TUllery** [comment]
I do not see how this and issue #15 are related. Again, I don't want Issue #15 changes. For this issue, I see two options. Option 1, stay with the existing email defines user premise where a new email address would become a new user - period. Option 2, update the User schema to use a primary key field instead of the email to link the functionality. Would need to keep the old email until the new one is confirmed. This may be too complicated for what it is worth. I don't see anyone changing their email.

**Comment by lgartrell** [comment]
@TUllery if there is an option to change their email I think this is a case we need to fix. If they can't change their email currently, then we can put this to the back burner but losing all appointments by updating user information sounds like a problem to me.

I originally thought this and #15 were related because they both involved changing the User Schema, but that was before I found out we already did #15.
